// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createFallbackClient = () => ({
  from: () => ({
    insert: async () => ({ data: null, error: new Error("Supabase is not configured") }),
    select: async () => ({ data: null, error: new Error("Supabase is not configured") }),
    update: async () => ({ data: null, error: new Error("Supabase is not configured") }),
    delete: async () => ({ data: null, error: new Error("Supabase is not configured") }),
    eq: () => createFallbackClient().from(),
  }),
});

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : (createFallbackClient() as any);